name: Build and Test

on:
  push:
    branches: ["main", "master", "develop"]
  pull_request:
    branches: ["main", "master", "develop"]

jobs:
  node-setup:
    uses: kientrant1/central-ops/.github/workflows/node-setup.yml@main
    with:
      node-version: "20.x"

  build:
    name: Build Project
    needs: node-setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run:
          yarn install
    
      - name: Run ESLint
        run:
          yarn lint

      - name: Build Storybook
        run:
          yarn build:storybook

      - name: Build Library
        run:
          yarn build:lib