name: Bump Version and Create Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Bump Version Type"
        required: true
        # default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  bump-version:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # needed for tags

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Bump Version in Package JSON (no git commit)
        id: bump
        run: |
          new_version=$(npm version ${{ github.event.inputs.release_type }} --no-git-tag-version)
          echo "new_version=${new_version}" >> $GITHUB_OUTPUT

      - name: Configure Git User
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@bot.noreply.github.com"
      
      - name: Commit Version Bump
        # git add package.json package.lock.json || true
        run: |
          git add package.json || true
          git commit -m "chore(release): bump version ${{ steps.bump.outputs.new_version }}"
      
      - name: Create Tag
        run: |
          git tag ${{ steps.bump.outputs.new_version }}
      - name: Push Commit And Tag
        run: |
          git push origin HEAD
          git push origin ${{ steps.bump.outputs.new_version }}

      - name: Create Draft GitHub Release 
        # No trigger publish workflow
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.bump.outputs.new_version }}
          name: Release ${{ steps.bump.outputs.new_version }}
          generate_release_notes: true
          draft: true
